### ISSUE TITLE
Include Fixed Vanilla ESMs

### ISSUE THREAD

**Issue by zpok3** [Baestus/viva-new-vegas-wabbajack-test#1]
This is probably abandoned but Wabbajack is able to binary patch esms and esps, effectively automating the Ultimate Edition ESM Fixes step. More info is in the Wabbajack documentation [here](https://wiki.wabbajack.org/modlist_author_documentation/Pre-Compilation.html#patches).

**Comment by Baestus** [comment]
Thanks for pointing this out. Unfortunately, when I attempted automating this step with Wabbajack as described, I was running into some issues. 
As it turns out, the BSAs from BSA Decompressor were the issue, not the Fixed ESMs. I'm re-creating the .wabbajack right now to see if I can get it to function with the ESMs modified. If I can, I'll update with a new version. 

I see you have made your own unofficial Wabbajack for VNV, and it looks significantly more professional. I'll leave this one up for posterity, and update it upon request, but it looks like you've got the Wabbajack covered. 
Thank you for you work!

**Comment by Baestus** [comment]
Added in release 0.74.
